version: "3.8"

services:
    webserver:
        container_name: picu_web
        build:
            context: ./docker/php
        restart: 'always'
        ports:
            - '80:80'
        links:
            - database
        volumes:
            - ./src:/var/www/html/picu:rw
            - ./gallery:/var/www/html/galerii:rw
            - ./docker/php/php.ini:/usr/local/etc/php/php.ini
            - ./docker/apache/vhosts:/etc/apache2/sites-enabled
        environment:
            APACHE_DOCUMENT_ROOT: /var/www/html
            MYSQL_ROOT_PASSWORD: tiger
            MYSQL_USER: picu
            MYSQL_PASSWORD: picu
            MYSQL_DATABASE: picu
            HOST_MACHINE_MYSQL_PORT: 3306
        extra_hosts:
            - 'host.docker.internal:host-gateway'
    database:
        container_name: picu_db
        image: mariadb:10.9
        ports:
            - '3306:3306'
        environment:
            - MYSQL_ROOT_PASSWORD=tiger
            - MYSQL_DATABASE=picu
            - MYSQL_USER=picu
            - MYSQL_PASSWORD=picu
        volumes:
            - './docker/dbdata:/var/lib/mysql'

